Add TLS auth for docker host

diff --git a/assets/out b/assets/out
--- a/assets/out
+++ b/assets/out
@@ -218,6 +218,21 @@ validate_command() {
   esac
 }
 
+tlsverify() {
+  local tls=$(jq -r '.source.tlsverify // ""' < $payload)
+  [ -z "$tls" ] && return
+  local client_home="$HOME/.docker"
+  mkdir -p "$client_home"
+  
+  for key in ca cert key; do
+    local value=$(jq -r ".source.tlsverify.${key}" < $payload)
+    [ -z "$value" ] && echo "ERROR: 'source.tlsverify.$key' must be defined" && exit 1
+    echo "$value" > "${client_home}/${key}.pem"
+  done
+
+  echo -n "--tlsverify "
+}
+
 host=$(jq -r '.source.host // ""' < $payload)
 test -z "$host" && { echo '"source.host" must be defined' >&2; exit 1; }
 port=$(jq -r '.source.port // "2376"' < $payload)
@@ -260,6 +275,7 @@ fi
 docker-compose \
   --host $host:$port \
   -f $compose_file \
+  $(tlsverify) \
   $(verbose_option) \
   $(project_option) \
   $(command_arguments $command);
